<a href="https://colab.research.google.com/github/maya-25/Website_Phishing_detection_ML/blob/main/Website_phishing_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#website phishing detection using .arff dataset containing 37 different features which can help in detecting malicious website

!pip install liac-arff

  Created wheel for liac-arff: filename=liac_arff-2.5.0-cp37-none-any.whl size=11732 sha256=efac250f6e62707fd7a61243fa8206d96494da9214f3e2ec5baafd51c3942659
  Stored in directory: /root/.cache/pip/wheels/77/8d/b4/8bfce5beea9a3496cc15b24961876adb7b6e2912ff09164179
Successfully built liac-arff


In [7]:
import arff
import pandas as pd
import numpy as np

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
dataset = arff.load(open("/content/drive/My Drive/Training Dataset.arff"))

In [ ]:
df = pd.DataFrame(dataset['attributes'])

In [ ]:
df

0           1
0             having_IP_Address     [-1, 1]
1                    URL_Length  [1, 0, -1]
2            Shortining_Service     [1, -1]
3              having_At_Symbol     [1, -1]
4      double_slash_redirecting     [-1, 1]
5                 Prefix_Suffix     [-1, 1]
6             having_Sub_Domain  [-1, 0, 1]
7                SSLfinal_State  [-1, 1, 0]
8   Domain_registeration_length     [-1, 1]
9                       Favicon     [1, -1]
10                         port     [1, -1]
11                  HTTPS_token     [-1, 1]
12                  Request_URL     [1, -1]
13                URL_of_Anchor  [-1, 0, 1]
14                Links_in_tags  [1, -1, 0]
15                          SFH  [-1, 1, 0]
16          Submitting_to_email     [-1, 1]
17                 Abnormal_URL     [-1, 1]
18                     Redirect      [0, 1]
19                 on_mouseover     [1, -1]
20                   RightClick     [1, -1]
21                  popUpWidnow     [1, -1]
22                       Iframe     [1, -1]
23                age_of_domain     [-1, 1]
24                    DNSRecord     [-1, 1]
25                  web_traffic  [-1, 0, 1]
26                    Page_Rank     [-1, 1]
27                 Google_Index     [1, -1]
28       Links_pointing_to_page  [1, 0, -1]
29           Statistical_report     [-1, 1]
30                       Result     [-1, 1]

In [ ]:
df = pd.DataFrame(dataset['data'])

In [ ]:
df

0   1   2   3   4   5   6   7   8   ...  22  23  24  25  26  27  28  29  30
0      -1   1   1   1  -1  -1  -1  -1  -1  ...   1  -1  -1  -1  -1   1   1  -1  -1
1       1   1   1   1   1  -1   0   1  -1  ...   1  -1  -1   0  -1   1   1   1  -1
2       1   0   1   1   1  -1  -1  -1  -1  ...   1   1  -1   1  -1   1   0  -1  -1
3       1   0   1   1   1  -1  -1  -1   1  ...   1  -1  -1   1  -1   1  -1   1  -1
4       1   0  -1   1   1  -1   1   1  -1  ...   1  -1  -1   0  -1   1   1   1   1
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
11050   1  -1   1  -1   1   1   1   1  -1  ...  -1   1   1  -1  -1   1   1   1   1
11051  -1   1   1  -1  -1  -1   1  -1  -1  ...   1   1   1   1   1   1  -1   1  -1
11052   1  -1   1   1   1  -1   1  -1  -1  ...   1   1   1   1  -1   1   0   1  -1
11053  -1  -1   1   1   1  -1  -1  -1   1  ...   1   1   1   1  -1   1   1   1  -1
11054  -1  -1   1   1   1  -1  -1  -1   1  ...   1  -1   1  -1  -1  -1   1  -1  -1

[11055 rows x 31 columns]

In [ ]:
dict = {df.columns[0]: 'having_IP_Address',
        df.columns[1]: 'URL_Length',
        df.columns[2]: 'Shortining_Service',
        df.columns[3]:'having_At_Symbol',
        df.columns[4]:'double_slash_redirecting',
        df.columns[5]:'Prefix_Suffix',
        df.columns[6]:'having_Sub_Domain',
        df.columns[7]:'SSLfinal_State',
        df.columns[8]:'Domain_registeration_length',
        df.columns[9]:'Favicon',
        df.columns[10]:'port',
        df.columns[11]:'HTTPS_token',
        df.columns[12]:'Request_URL',
        df.columns[13]:'URL_of_Anchor',
        df.columns[14]:'Links_in_tags',
        df.columns[15]:'SFH',
        df.columns[16]:'Submitting_to_email',
        df.columns[17]:'Abnormal_URL',
        df.columns[18]:'Redirect',
        df.columns[19]:'on_mouseover',
        df.columns[20]:'RightClick',
        df.columns[21]:'popUpWidnow',
        df.columns[22]:'Iframe',
        df.columns[23]:'age_of_domain',
        df.columns[24]:'DNSRecord',
        df.columns[25]:'web_traffic',
        df.columns[26]:'Page_Rank',
        df.columns[27]:'Google_Index',
        df.columns[28]:'Links_pointing_to_page',
        df.columns[29]:'Statistical_report',
        df.columns[30]:'Result'}

In [ ]:
df.rename(columns=dict,inplace=True)

In [ ]:
df

having_IP_Address URL_Length  ... Statistical_report Result
0                    -1          1  ...                 -1     -1
1                     1          1  ...                  1     -1
2                     1          0  ...                 -1     -1
3                     1          0  ...                  1     -1
4                     1          0  ...                  1      1
...                 ...        ...  ...                ...    ...
11050                 1         -1  ...                  1      1
11051                -1          1  ...                  1     -1
11052                 1         -1  ...                  1     -1
11053                -1         -1  ...                  1     -1
11054                -1         -1  ...                 -1     -1

[11055 rows x 31 columns]

In [ ]:
df.columns

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [ ]:
df['Result'].value_counts()

1     6157
-1    4898
Name: Result, dtype: int64

In [ ]:
def convertEncodingToPositive(dataframe):

  mapping = {-1: 2, 0: 0, 1: 1}

  col_map = {}

  for col in dataframe:
    col_map[col] = mapping

  for i in range(dataframe.shape[0]):
    # if (i%100 == 0):
    #   print(i)
    for j in range(dataframe.shape[1]):
      dataframe.loc[i][j] = mapping[dataframe.loc[i][j]]

In [ ]:
for col in df.columns:
  df[col] = df[col].astype(int)

In [ ]:
#replacing negative value -1 to 2

df[df<0]=2

In [ ]:
df

having_IP_Address  URL_Length  ...  Statistical_report  Result
0                      2           1  ...                   2       2
1                      1           1  ...                   1       2
2                      1           0  ...                   2       2
3                      1           0  ...                   1       2
4                      1           0  ...                   1       1
...                  ...         ...  ...                 ...     ...
11050                  1           2  ...                   1       1
11051                  2           1  ...                   1       2
11052                  1           2  ...                   1       2
11053                  2           2  ...                   1       2
11054                  2           2  ...                   2       2

[11055 rows x 31 columns]

In [ ]:
reduced_cols=df[['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email','on_mouseover', 'RightClick', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank', 'Statistical_report',
       'Result']]

In [ ]:
reduced_cols

having_IP_Address  URL_Length  ...  Statistical_report  Result
0                      2           1  ...                   2       2
1                      1           1  ...                   1       2
2                      1           0  ...                   2       2
3                      1           0  ...                   1       2
4                      1           0  ...                   1       1
...                  ...         ...  ...                 ...     ...
11050                  1           2  ...                   1       1
11051                  2           1  ...                   1       2
11052                  1           2  ...                   1       2
11053                  2           2  ...                   1       2
11054                  2           2  ...                   2       2

[11055 rows x 25 columns]

In [ ]:
reduced_cols.to_csv("Phising_test.csv")

In [ ]:
import sklearn

In [ ]:
sklearn.__version__

'0.22.2.post1'

In [ ]:
from sklearn.model_selection import train_test_split, KFold

In [ ]:
X_reduced = reduced_cols.iloc[:,0:24]
y_reduced = reduced_cols.iloc[:, -1]

In [ ]:
X_reduced,y_reduced

(       having_IP_Address  URL_Length  ...  Page_Rank  Statistical_report
 0                      2           1  ...          2                   2
 1                      1           1  ...          2                   1
 2                      1           0  ...          2                   2
 3                      1           0  ...          2                   1
 4                      1           0  ...          2                   1
 ...                  ...         ...  ...        ...                 ...
 11050                  1           2  ...          2                   1
 11051                  2           1  ...          1                   1
 11052                  1           2  ...          2                   1
 11053                  2           2  ...          2                   1
 11054                  2           2  ...          2                   2
 
 [11055 rows x 24 columns], 0        2
 1        2
 2        2
 3        2
 4        1
         ..
 11050    1

In [ ]:
X_train_red, X_test_red, y_train_red, y_test_red = train_test_split(X_reduced, y_reduced, test_size=0.2, random_state=7, stratify=y_reduced)

In [ ]:
X_test_red.shape

(2211, 25)

In [ ]:
kf = KFold(n_splits=5, shuffle=True, random_state=786)

In [ ]:
X_train_red = X_train_red.to_numpy()
X_test_red = X_test_red.to_numpy()
y_train_red = y_train_red.to_numpy()
y_test_red = y_test_red.to_numpy()

In [ ]:
X_train_red

array([[2, 2, 1, ..., 0, 2, 1],
       [1, 2, 1, ..., 2, 2, 2],
       [2, 2, 1, ..., 0, 2, 1],
       ...,
       [2, 1, 2, ..., 1, 2, 1],
       [1, 2, 1, ..., 2, 2, 1],
       [2, 2, 2, ..., 1, 1, 1]])

In [ ]:
for train, test in kf.split(X_train_red):
  print(X_train_red[train].shape, y_train_red[train].shape, X_train_red[test].shape, y_train_red[test].shape)

(7075, 24) (7075,) (1769, 24) (1769,)
(7075, 24) (7075,) (1769, 24) (1769,)
(7075, 24) (7075,) (1769, 24) (1769,)
(7075, 24) (7075,) (1769, 24) (1769,)
(7076, 24) (7076,) (1768, 24) (1768,)


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn import metrics
from pprint import pprint
from sklearn.naive_bayes import CategoricalNB

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
import pickle
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
X_train_red_onehot = encoder.fit_transform(X_train_red)
X_test_red_onehot = encoder.transform(X_test_red)
pickle.dump(encoder, open("One_Hot_Encoder", 'wb'))

In [ ]:
def gridsearch_KNN(X_train_red_onehot, y_train_red):
  clf_knn = KNeighborsClassifier()
  knn_param_grid = {
      "n_neighbors": [3, 5, 7, 9, 15],
      "metric": ['euclidean', 'manhattan']
  }

  gs_knn = GridSearchCV(KNeighborsClassifier(), knn_param_grid, cv = 3)
  gs_results = gs_knn.fit(X_train_red_onehot, y_train_red)

  return gs_results.best_params_

bestparams_knn = gridsearch_KNN(X_train_red_onehot, y_train_red)
print(bestparams_knn)

{'metric': 'euclidean', 'n_neighbors': 3}


In [ ]:
def to_use_KNN(X_train_red_onehot, y_train_red):
  accuracy_scores_catKNN = []
  for train, val in kf.split(X_train_red):
    clf_neigh = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
    clf_neigh = clf_neigh.fit(X_train_red_onehot[train], y_train_red[train])
    tp, fn, fp, tn = metrics.confusion_matrix(y_train_red[val], clf_neigh.predict(X_train_red_onehot[val])).ravel()
    accuracy = (tn+tp)/(fp+fn+tp+tn)
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    fpr = fp/(fp+tn)
    f1 = 2*precision*recall/(precision + recall)
    accuracy_scores_catKNN.append((accuracy, precision, recall, fpr, f1))
  
  return np.mean(accuracy_scores_catKNN, axis=0)

metric_knn = to_use_KNN(X_train_red_onehot, y_train_red)
print(metric_knn)

[0.95624142 0.95444532 0.96745392 0.0577831  0.9608973 ]


In [ ]:
from xgboost import XGBClassifier

In [ ]:
def to_use_XGB(X_train_red_onehot, y_train_red):
  accuracy_scores_xgb = []
  for train, val in kf.split(X_train_red):
    clf_xgb = XGBClassifier(silent=False, 
                        scale_pos_weight=1,
                        learning_rate=0.01,  
                        colsample_bytree = 0.4,
                        subsample = 0.8,
                        objective='binary:logistic', 
                        n_estimators=1000, 
                        reg_alpha = 0.3,
                        max_depth=4, 
                        gamma=10)
    clf_xgb = clf_xgb.fit(X_train_red_onehot[train], y_train_red[train])
    tp, fn, fp, tn = metrics.confusion_matrix(y_train_red[val], clf_xgb.predict(X_train_red_onehot[val])).ravel()
    accuracy = (tn+tp)/(fp+fn+tp+tn)
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    fpr = fp/(fp+tn)
    f1 = 2*precision*recall/(precision + recall)
    accuracy_scores_xgb.append((accuracy, precision, recall, fpr, f1))

    return np.mean(accuracy_scores_xgb, axis=0)
    
metric_xgb = to_use_XGB(X_train_red_onehot, y_train_red)
print(metric_xgb)

[0.95421142 0.95579568 0.96432111 0.05921053 0.96003947]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
def grid_search_decision_tree(X_train_red_onehot, y_train_red):
  dt = DecisionTreeClassifier(random_state=5)
  p = {"max_depth": range(1,20), "random_state":[5]}
  gs = GridSearchCV(estimator=dt,param_grid=p)
  gs_fit = gs.fit(X_train_red, y_train_red)
  return gs_fit.best_params_

best_params_decision_tree = grid_search_decision_tree(X_train_red_onehot, y_train_red)
print(best_params_decision_tree)

{'max_depth': 17, 'random_state': 5}


In [ ]:
def to_use_decisiontree(X_train_red_onehot, y_train_red):
  accuracy_scores_dt = []
  for train, val in kf.split(X_train_red):
      dt = DecisionTreeClassifier(random_state=5, max_depth=17)
      dt = dt.fit(X_train_red[train], y_train_red[train])
      tp, fn, fp, tn = metrics.confusion_matrix(y_train_red[val],dt.predict(X_train_red[val])).ravel()
      dt_accuracy = (tn+tp)/(tp+tn+fp+fn)
      dt_prec = tp/(tp+fp)
      dt_rec = tp/(tp+fn)
      dt_fpr = fp/(fp+tn)
      dt_f1 = 2*dt_prec*dt_rec/(dt_prec+dt_rec)
      accuracy_scores_dt.append((dt_accuracy,dt_prec,dt_rec,dt_fpr,dt_f1))
  
  return np.mean(accuracy_scores_dt,axis=0)

metric_decision_tree = to_use_decisiontree(X_train_red_onehot, y_train_red)
print(metric_decision_tree)

[0.95759837 0.95687342 0.96759805 0.05486563 0.96216162]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
def grid_search_random_forest(X_train_red_onehot, y_train_red):
  rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True) 
  param_grid = { 
      'n_estimators': [200, 700],
      'max_features': ['auto', 'sqrt', 'log2']
  }
  CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
  CV_rfc.fit(X_train_red, y_train_red)
  return CV_rfc.best_params_

best_params_rfc = grid_search_random_forest(X_train_red_onehot, y_train_red)
print(best_params_rfc)

{'max_features': 'sqrt', 'n_estimators': 200}


In [ ]:
def to_use_rfc(X_train_red_onehot, y_train_red):
  accuracy_scores_forest = []
  for train, val in kf.split(X_train_red):
      rforest = RandomForestClassifier(max_features= 'sqrt' ,n_estimators=200)
      rforest = rforest.fit(X_train_red_onehot[train],y_train_red[train])
      tp1, fn1, fp1, tn1 = metrics.confusion_matrix(y_train_red[val],rforest.predict(X_train_red_onehot[val])).ravel()
      r_accuracy = (tn1 + tp1)/(tn1+tp1+fn1+fp1)
      r_prec = tp1/(tp1+fp1)
      r_rec = tp1/(tp1+fn1)
      r_fpr = fp1/(fp1+tn1)
      r_f1 = 2*(r_prec)*r_rec/(r_prec+r_rec)
      accuracy_scores_forest.append((r_accuracy,r_prec,r_rec,r_fpr,r_f1))

  return np.mean(accuracy_scores_forest, axis=0)
  

metric_rforest = to_use_rfc(X_train_red_onehot, y_train_red)
print(metric_rforest)

[0.96709616 0.96449627 0.97687795 0.04513165 0.97063572]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from pprint import pprint

In [ ]:
def to_use_logistic(X_train_red_onehot, y_train_red):

  accuracy_scores_log = []
  for train, val in kf.split(X_train_red_onehot):
    log = LogisticRegression(max_iter = 2500)
    log = log.fit(X_train_red_onehot[train], y_train_red[train])
    tp, fn, fp, tn = metrics.confusion_matrix(y_train_red[val], log.predict(X_train_red_onehot[val])).ravel()
    accuracy = (tn+tp)/(fp+fn+tp+tn)
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    fpr = fp/(fp+tn)
    f1 = 2*precision*recall/(precision + recall)
    accuracy_scores_log.append((accuracy, precision, recall, fpr, f1))
  
  return np.mean(accuracy_scores_log, axis=0)

metric_logistic = to_use_logistic(X_train_red_onehot, y_train_red)
print(metric_logistic)

[0.93611405 0.93730173 0.94853572 0.07949822 0.9428815 ]


In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [ ]:
!pip uninstall sklearn==0.22.2.post1

Uninstalling sklearn-0.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/sklearn-0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled sklearn-0.0


In [ ]:
!pip install scikit-learn==0.22

     |████████████████████████████████| 7.0MB 3.9MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:
import sklearn
sklearn.__version__

'0.22.2.post1'

In [ ]:
def grid_search_svm(X_train_red_onehot, y_train_red):
  svm_clf = svm.SVC()
  param_grid = {'C': [0.1, 1, 10, 100],  
                'gamma': [1, 0.1, 0.01, 0.001], 
                'kernel': ['rbf', 'linear']}  

  gs_svm = GridSearchCV(svm.SVC(), param_grid, cv = 3)
  gs_results = gs_svm.fit(X_train_red_onehot, y_train_red)

  return gs_results.best_params_

bestparams_svm = grid_search_svm(X_train_red_onehot, y_train_red)
print(bestparams_svm)

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}


In [ ]:
def to_use_SVM(X_train_red_onehot, y_train_red):
  accuracy_scores_svm = []
  for train, val in kf.split(X_train_red_onehot):
    svm_clf = svm.SVC(kernel='rbf', gamma = 0.1, C = 10, probability=False)
    svm_clf = svm_clf.fit(X_train_red_onehot[train], y_train_red[train])
    tp, fn, fp, tn = metrics.confusion_matrix(y_train_red[val], svm_clf.predict(X_train_red_onehot[val])).ravel()
    
    accuracy = (tn+tp)/(fp+fn+tp+tn)
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    fpr = fp/(fp+tn)
    f1 = 2*precision*recall/(precision + recall)
    accuracy_scores_svm.append((accuracy, precision, recall, fpr, f1))


  return np.mean(accuracy_scores_svm, axis=0)

metric_svm = to_use_SVM(X_train_red_onehot, y_train_red)
print(metric_svm)

[0.9629123  0.96513497 0.9682808  0.04380424 0.96669704]


In [ ]:
def to_test_SVM(X_test_red_onehot, y_test_red, X_train_red_onehot, y_train_red):  
  svm_clf = svm.SVC(kernel='rbf', gamma = 0.1, C = 10, probability=False)
  svm_clf = svm_clf.fit(X_train_red_onehot, y_train_red)
  tp, fn, fp, tn = metrics.confusion_matrix(y_test_red, svm_clf.predict(X_test_red_onehot)).ravel()
  accuracy = (tn+tp)/(fp+fn+tp+tn)
  precision = tp/(tp+fp)
  recall = tp/(tp+fn)
  fpr = fp/(fp+tn)
  f1 = 2*precision*recall/(precision + recall)
  pickle.dump(svm_clf, open("SVM_Final_Model", 'wb'))
  return accuracy

test_accuracy = to_test_SVM(X_test_red_onehot, y_test_red, X_train_red_onehot, y_train_red)
print(test_accuracy)

0.9611035730438715


In [ ]:
import pickle

In [ ]:
filename_dt = 'SVM_Final_Model'
loaded_model = pickle.load(open(filename_dt, 'rb'))
tp, fn, fp, tn = metrics.confusion_matrix(y_test_red, loaded_model.predict(X_test_red_onehot)).ravel()
accuracy = (tn+tp)/(fp+fn+tp+tn)
recall = tp/(tp+fn)
fpr = fp/(fp+tn)
print(accuracy)
print(recall)
print(fpr)
print(loaded_model.predict(X_test_red_onehot))

0.9611035730438715
0.9626320064987814
0.04081632653061224
[2 1 2 ... 1 1 1]


In [ ]:
X_test1=encoder.inverse_transform(X_test_red_onehot).astype(int).shape[1]

In [ ]:
np.savetxt("test_data.csv", X_test_red_onehot, delimiter="," ,header='True')